# Generated by Django 5.1.6 on 2025-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('wage_id', models.AutoField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Full Payment', 'Full Payment'), ('Installment', 'Installment')], max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('wage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.wage')),
            ],
        ),
    ]
